In [1]:
import torch
z3 = torch.randn(10,1)
a3 = torch.sigmoid(z3)
print(a3)
print(a3.shape)

tensor([[0.2192],
        [0.5132],
        [0.3959],
        [0.4095],
        [0.5974],
        [0.7713],
        [0.6621],
        [0.5430],
        [0.4814],
        [0.1024]])
torch.Size([10, 1])


In [2]:
torch.mean(a3).item()

0.4695364832878113

In [3]:
keepprob = 0.8
d3 = torch.randn(a3.shape[0], a3.shape[1])
print(d3)

tensor([[ 1.4875],
        [ 0.0606],
        [-0.1991],
        [ 1.0537],
        [-0.4122],
        [-0.0351],
        [ 0.9415],
        [ 0.0537],
        [-0.8175],
        [-0.3220]])


In [4]:
d3 = d3 < keepprob 
print(d3)

tensor([[False],
        [ True],
        [ True],
        [False],
        [ True],
        [ True],
        [False],
        [ True],
        [ True],
        [ True]])


In [5]:
False == 0

True

In [6]:
1 == True

True

In [7]:
a3 = torch.mul(a3, d3)
print(a3)
print(torch.mean(a3).item())

tensor([[0.0000],
        [0.5132],
        [0.3959],
        [0.0000],
        [0.5974],
        [0.7713],
        [0.0000],
        [0.5430],
        [0.4814],
        [0.1024]])
0.3404501676559448


In [8]:
a3 = a3/keepprob
print(a3)
print(torch.mean(a3).item())

tensor([[0.0000],
        [0.6415],
        [0.4948],
        [0.0000],
        [0.7468],
        [0.9641],
        [0.0000],
        [0.6787],
        [0.6018],
        [0.1279]])
0.42556267976760864
