## Vectorization

In [1]:
import torch
import numpy as np

a = np.array([1, 2, 3, 4])
b = torch.tensor([1, 2, 3, 4])

In [2]:
mynum = 1000000000

In [3]:
na = np.random.randn(mynum)
nb = np.random.randn(mynum)
ta = torch.tensor(na)
tb = torch.tensor(nb)

In [4]:
def for_loop(a,b):
    total = 0 
    for i in range(len(a)):
        total += a[i]*b[i]    
    return round(total)
def np_dot_product(a,b):
    return np.round(np.dot(a,b))
def torch_dot_product(a, b):
    return torch.round(torch.matmul(a,b)).item()

In [5]:
%%time
print("Torch Vectorized version:")
c = torch_dot_product(ta,tb)
print(c)

Torch Vectorized version:
-11641.0
Wall time: 21.8 s


In [6]:
%%time
print("Numpy Vectorized version:")
c = np_dot_product(na,nb)
print(c)

Numpy Vectorized version:
-11641.0
Wall time: 59.2 s


In [7]:
%%time
print("Not vectorized version: ")
d = for_loop(na, nb)
print(d)

Not vectorized version: 
-11641.0
Wall time: 8min 29s


## Broadcasting

In [8]:
A = torch.tensor([[56.0, 0.0, 4.4, 68.0],
             [1.2, 104.0, 52.0, 8.0],
             [1.8, 135.0, 99.0, 0.9]])
print(A)

tensor([[ 56.0000,   0.0000,   4.4000,  68.0000],
        [  1.2000, 104.0000,  52.0000,   8.0000],
        [  1.8000, 135.0000,  99.0000,   0.9000]])


In [9]:
cal = A.sum(axis = 0) # sum vertically
print(cal)

tensor([ 59.0000, 239.0000, 155.4000,  76.9000])


In [10]:
percentage = 100*A/cal # broadcasting
print(percentage)

tensor([[94.9153,  0.0000,  2.8314, 88.4265],
        [ 2.0339, 43.5146, 33.4620, 10.4031],
        [ 3.0508, 56.4854, 63.7066,  1.1704]])


###### (3,4) / (1,4) !?!?!?!? IMPOSSIBLE

## Debugging torch -- be explicit with vector shapes

In [11]:
a = torch.rand(5)
print(a)

tensor([0.3298, 0.5748, 0.4428, 0.3709, 0.2817])


In [12]:
print(a.shape) # rank 1 array, neither row nor column vector

torch.Size([5])


In [13]:
print(a.T.shape)

torch.Size([5])


In [14]:
#5x1 X 1x5??
print(torch.matmul(a, a.T))

tensor(0.8522)


In [15]:
assert(a.shape == (5,1))

AssertionError: 

In [16]:
a = a.reshape((5,1))

In [17]:
assert(a.shape == (5,1))

In [18]:
a = torch.rand(5, 1)
print(a)

tensor([[0.8498],
        [0.1439],
        [0.7941],
        [0.0479],
        [0.9192]])


In [19]:
print(a.T)

tensor([[0.8498, 0.1439, 0.7941, 0.0479, 0.9192]])


In [20]:
print(torch.matmul(a, a.T))

tensor([[0.7221, 0.1223, 0.6748, 0.0407, 0.7811],
        [0.1223, 0.0207, 0.1142, 0.0069, 0.1323],
        [0.6748, 0.1142, 0.6305, 0.0380, 0.7299],
        [0.0407, 0.0069, 0.0380, 0.0023, 0.0440],
        [0.7811, 0.1323, 0.7299, 0.0440, 0.8449]])


In [21]:
assert(a.shape == (5,1))